### ISSUE TITLE
irrelevant ld comparison

### ISSUE THREAD

**Issue by Pshriwise** [svalinn/condorht_tools#39]
There is an un-necessary comparison of the meshtal ld values when combining meshtal files in [streaming mode](https://github.com/svalinn/condorht_tools/blob/master/combine/meshtal_combine.py#L316).

This should probably be removed. There is a similar case in the non [streaming mode](https://github.com/svalinn/condorht_tools/blob/master/combine/meshtal_combine.py#L153) as well.

**Comment by makeclean** [comment]
Fixed
