### ISSUE TITLE
incorrect averaging method in meshtal_combine

### ISSUE THREAD

**Issue by Pshriwise** [svalinn/condorht_tools#41]
Meshtal combine should be limited to no more than 2 meshes if doing an average. The current effective math (for a set of meshtals with an equal number of histories) is: 

(((a+b)/2 + c)/2 + d)/2 = a/8 + b/8+ c/4 + d/2
rather than 
(a+b+c+d)/4

PR to come.

**Comment by makeclean** [comment]
Fixed.
